// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WarehousePOS.Data;

#nullable disable

namespace WarehousePOS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260122235145_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WarehousePOS.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("customer_code");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("customer_name");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<int?>("TierId")
                        .HasColumnType("int")
                        .HasColumnName("tier_id");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("int")
                        .HasColumnName("total_points");

                    b.Property<decimal>("TotalPurchase")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("total_purchase");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.HasIndex("CustomerCode")
                        .IsUnique();

                    b.HasIndex("TierId");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("WarehousePOS.Models.CustomerTier", b =>
                {
                    b.Property<int>("TierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tier_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TierId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("discount_percentage");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<int>("MinPoints")
                        .HasColumnType("int")
                        .HasColumnName("min_points");

                    b.Property<string>("TierDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tier_description");

                    b.Property<string>("TierName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tier_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("TierId");

                    b.ToTable("customer_tiers");
                });

            modelBuilder.Entity("WarehousePOS.Models.Order", b =>
                {
                    b.Property<long>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OrderId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<int?>("CustomerTierId")
                        .HasColumnType("int")
                        .HasColumnName("customer_tier_id");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("discount_amount");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("order_date");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("order_number");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("order_status");

                    b.Property<int>("OrderTypeId")
                        .HasColumnType("int")
                        .HasColumnName("order_type_id");

                    b.Property<int>("OutletId")
                        .HasColumnType("int")
                        .HasColumnName("outlet_id");

                    b.Property<decimal>("ShippingAmount")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("shipping_amount");

                    b.Property<decimal>("SubtotalAmount")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("subtotal_amount");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("tax_amount");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("total_amount");

                    b.Property<int>("TotalItems")
                        .HasColumnType("int")
                        .HasColumnName("total_items");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("CustomerTierId");

                    b.HasIndex("OrderDate");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("OrderStatus");

                    b.HasIndex("OrderTypeId");

                    b.HasIndex("OutletId");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("WarehousePOS.Models.OrderDetail", b =>
                {
                    b.Property<long>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("order_detail_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OrderDetailId"));

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("discount_amount");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("discount_percentage");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int?>("ProductId1")
                        .HasColumnType("int");

                    b.Property<int?>("ProductVariantVariantId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("quantity");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("unit_price");

                    b.Property<int?>("VariantId")
                        .HasColumnType("int")
                        .HasColumnName("variant_id");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductId1");

                    b.HasIndex("ProductVariantVariantId");

                    b.HasIndex("VariantId");

                    b.ToTable("order_details");
                });

            modelBuilder.Entity("WarehousePOS.Models.OrderPayment", b =>
                {
                    b.Property<long>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("payment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PaymentId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("payment_amount");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("payment_date");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("int")
                        .HasColumnName("payment_method_id");

                    b.Property<int?>("PaymentMethodMethodId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payment_status");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("reference_number");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.HasIndex("OrderId");

                    b.HasIndex("PaymentDate");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("PaymentMethodMethodId");

                    b.ToTable("order_payments");
                });

            modelBuilder.Entity("WarehousePOS.Models.OrderReturn", b =>
                {
                    b.Property<long>("ReturnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("return_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ReturnId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("return_date");

                    b.Property<string>("ReturnNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("return_number");

                    b.Property<string>("ReturnReason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("return_reason");

                    b.Property<string>("ReturnStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("return_status");

                    b.Property<decimal>("TotalRefundAmount")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("total_refund_amount");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("ReturnId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ReturnDate");

                    b.HasIndex("ReturnNumber")
                        .IsUnique();

                    b.ToTable("order_returns");
                });

            modelBuilder.Entity("WarehousePOS.Models.OrderType", b =>
                {
                    b.Property<int>("OrderTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("order_type_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderTypeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("type_code");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("type_name");

                    b.HasKey("OrderTypeId");

                    b.ToTable("order_types");
                });

            modelBuilder.Entity("WarehousePOS.Models.Outlet", b =>
                {
                    b.Property<int>("OutletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("outlet_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OutletId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("OutletCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("outlet_code");

                    b.Property<string>("OutletName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("outlet_name");

                    b.Property<string>("OutletType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("outlet_type");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("OutletId");

                    b.HasIndex("OutletCode")
                        .IsUnique();

                    b.ToTable("outlets");
                });

            modelBuilder.Entity("WarehousePOS.Models.PaymentMethod", b =>
                {
                    b.Property<int>("MethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("method_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MethodId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("MethodCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("method_code");

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("method_name");

                    b.HasKey("MethodId");

                    b.ToTable("payment_methods");
                });

            modelBuilder.Entity("WarehousePOS.Models.PriceTier", b =>
                {
                    b.Property<int>("PriceTierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("price_tier_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PriceTierId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("TierDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tier_description");

                    b.Property<string>("TierName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tier_name");

                    b.HasKey("PriceTierId");

                    b.ToTable("price_tiers");
                });

            modelBuilder.Entity("WarehousePOS.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("BaseUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("base_unit");

                    b.Property<decimal>("ConversionFactor")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("conversion_factor");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("product_code");

                    b.Property<string>("ProductDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("product_description");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("product_name");

                    b.Property<int>("TypeId")
                        .HasColumnType("int")
                        .HasColumnName("type_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("ProductCode")
                        .IsUnique();

                    b.HasIndex("TypeId");

                    b.ToTable("products");
                });

            modelBuilder.Entity("WarehousePOS.Models.ProductPrice", b =>
                {
                    b.Property<int>("PriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("price_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PriceId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<int>("MinQuantity")
                        .HasColumnType("int")
                        .HasColumnName("min_quantity");

                    b.Property<int>("OutletId")
                        .HasColumnType("int")
                        .HasColumnName("outlet_id");

                    b.Property<int>("PriceTierId")
                        .HasColumnType("int")
                        .HasColumnName("price_tier_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int?>("ProductId1")
                        .HasColumnType("int");

                    b.Property<int?>("ProductVariantVariantId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("unit_price");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("VariantId")
                        .HasColumnType("int")
                        .HasColumnName("variant_id");

                    b.HasKey("PriceId");

                    b.HasIndex("OutletId");

                    b.HasIndex("PriceTierId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductId1");

                    b.HasIndex("ProductVariantVariantId");

                    b.HasIndex("VariantId");

                    b.ToTable("product_prices");
                });

            modelBuilder.Entity("WarehousePOS.Models.ProductStock", b =>
                {
                    b.Property<int>("StockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("stock_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockId"));

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_updated");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int")
                        .HasColumnName("location_id");

                    b.Property<decimal>("MaxStock")
                        .HasColumnType("decimal(15,4)")
                        .HasColumnName("max_stock");

                    b.Property<decimal>("MinStock")
                        .HasColumnType("decimal(15,4)")
                        .HasColumnName("min_stock");

                    b.Property<int>("OutletId")
                        .HasColumnType("int")
                        .HasColumnName("outlet_id");

                    b.Property<int?>("OutletId1")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int?>("ProductId1")
                        .HasColumnType("int");

                    b.Property<int?>("ProductVariantVariantId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(15,4)")
                        .HasColumnName("quantity");

                    b.Property<int?>("VariantId")
                        .HasColumnType("int")
                        .HasColumnName("variant_id");

                    b.HasKey("StockId");

                    b.HasIndex("LocationId");

                    b.HasIndex("OutletId");

                    b.HasIndex("OutletId1");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductId1");

                    b.HasIndex("ProductVariantVariantId");

                    b.HasIndex("VariantId");

                    b.ToTable("product_stocks");
                });

            modelBuilder.Entity("WarehousePOS.Models.ProductType", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("type_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("TypeDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type_description");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("type_name");

                    b.HasKey("TypeId");

                    b.ToTable("product_types");
                });

            modelBuilder.Entity("WarehousePOS.Models.ProductVariant", b =>
                {
                    b.Property<int>("VariantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("variant_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VariantId"));

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("barcode");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("VariantCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("variant_code");

                    b.Property<string>("VariantName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("variant_name");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("weight");

                    b.HasKey("VariantId");

                    b.HasIndex("Barcode");

                    b.HasIndex("ProductId");

                    b.HasIndex("VariantCode");

                    b.ToTable("product_variants");
                });

            modelBuilder.Entity("WarehousePOS.Models.Purchase", b =>
                {
                    b.Property<long>("PurchaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("purchase_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PurchaseId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<int>("OutletId")
                        .HasColumnType("int")
                        .HasColumnName("outlet_id");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("purchase_date");

                    b.Property<string>("PurchaseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("purchase_number");

                    b.Property<string>("PurchaseStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("purchase_status");

                    b.Property<DateTime?>("ReceivedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("received_date");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("supplier_id");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("PurchaseId");

                    b.HasIndex("OutletId");

                    b.HasIndex("PurchaseDate");

                    b.HasIndex("PurchaseNumber")
                        .IsUnique();

                    b.HasIndex("SupplierId");

                    b.ToTable("purchases");
                });

            modelBuilder.Entity("WarehousePOS.Models.PurchaseDetail", b =>
                {
                    b.Property<long>("PurchaseDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("purchase_detail_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PurchaseDetailId"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int?>("ProductId1")
                        .HasColumnType("int");

                    b.Property<int?>("ProductVariantVariantId")
                        .HasColumnType("int");

                    b.Property<long>("PurchaseId")
                        .HasColumnType("bigint")
                        .HasColumnName("purchase_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("quantity");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("unit_cost");

                    b.Property<int?>("VariantId")
                        .HasColumnType("int")
                        .HasColumnName("variant_id");

                    b.HasKey("PurchaseDetailId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductId1");

                    b.HasIndex("ProductVariantVariantId");

                    b.HasIndex("PurchaseId");

                    b.HasIndex("VariantId");

                    b.ToTable("purchase_details");
                });

            modelBuilder.Entity("WarehousePOS.Models.ReturnDetail", b =>
                {
                    b.Property<long>("ReturnDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("return_detail_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ReturnDetailId"));

                    b.Property<long>("OrderDetailId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_detail_id");

                    b.Property<long?>("OrderDetailId1")
                        .HasColumnType("bigint");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reason");

                    b.Property<decimal>("RefundAmount")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("refund_amount");

                    b.Property<long>("ReturnId")
                        .HasColumnType("bigint")
                        .HasColumnName("return_id");

                    b.Property<decimal>("ReturnQuantity")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("return_quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("unit_price");

                    b.Property<int?>("VariantId")
                        .HasColumnType("int")
                        .HasColumnName("variant_id");

                    b.HasKey("ReturnDetailId");

                    b.HasIndex("OrderDetailId");

                    b.HasIndex("OrderDetailId1");

                    b.HasIndex("ProductId");

                    b.HasIndex("ReturnId");

                    b.HasIndex("VariantId");

                    b.ToTable("return_details");
                });

            modelBuilder.Entity("WarehousePOS.Models.SoDetail", b =>
                {
                    b.Property<long>("SoDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("so_detail_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SoDetailId"));

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<decimal>("PhysicalQuantity")
                        .HasColumnType("decimal(15,4)")
                        .HasColumnName("physical_quantity");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int?>("ProductId1")
                        .HasColumnType("int");

                    b.Property<int?>("ProductVariantVariantId")
                        .HasColumnType("int");

                    b.Property<long>("SoId")
                        .HasColumnType("bigint")
                        .HasColumnName("so_id");

                    b.Property<decimal>("SystemQuantity")
                        .HasColumnType("decimal(15,4)")
                        .HasColumnName("system_quantity");

                    b.Property<decimal>("Variance")
                        .HasColumnType("decimal(15,4)")
                        .HasColumnName("variance");

                    b.Property<int?>("VariantId")
                        .HasColumnType("int")
                        .HasColumnName("variant_id");

                    b.HasKey("SoDetailId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductId1");

                    b.HasIndex("ProductVariantVariantId");

                    b.HasIndex("SoId");

                    b.HasIndex("VariantId");

                    b.ToTable("so_details");
                });

            modelBuilder.Entity("WarehousePOS.Models.StockLocation", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("location_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("location_code");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("location_name");

                    b.Property<int>("OutletId")
                        .HasColumnType("int")
                        .HasColumnName("outlet_id");

                    b.HasKey("LocationId");

                    b.HasIndex("OutletId");

                    b.ToTable("stock_locations");
                });

            modelBuilder.Entity("WarehousePOS.Models.StockLog", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("log_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LogId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int")
                        .HasColumnName("location_id");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<int>("OutletId")
                        .HasColumnType("int")
                        .HasColumnName("outlet_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int?>("ProductId1")
                        .HasColumnType("int");

                    b.Property<decimal>("QuantityAfter")
                        .HasColumnType("decimal(15,4)")
                        .HasColumnName("quantity_after");

                    b.Property<decimal>("QuantityBefore")
                        .HasColumnType("decimal(15,4)")
                        .HasColumnName("quantity_before");

                    b.Property<decimal>("QuantityChange")
                        .HasColumnType("decimal(15,4)")
                        .HasColumnName("quantity_change");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("reference_id");

                    b.Property<string>("ReferenceTable")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reference_table");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("transaction_type");

                    b.Property<int?>("VariantId")
                        .HasColumnType("int")
                        .HasColumnName("variant_id");

                    b.HasKey("LogId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("LocationId");

                    b.HasIndex("OutletId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductId1");

                    b.HasIndex("ReferenceId");

                    b.HasIndex("TransactionType");

                    b.HasIndex("VariantId");

                    b.ToTable("stock_logs");
                });

            modelBuilder.Entity("WarehousePOS.Models.StockOpname", b =>
                {
                    b.Property<long>("SoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("so_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SoId"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("completed_at");

                    b.Property<int?>("CompletedBy")
                        .HasColumnType("int")
                        .HasColumnName("completed_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<int>("OutletId")
                        .HasColumnType("int")
                        .HasColumnName("outlet_id");

                    b.Property<DateTime>("SoDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("so_date");

                    b.Property<string>("SoNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("so_number");

                    b.Property<string>("SoStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("so_status");

                    b.Property<decimal>("TotalVariance")
                        .HasColumnType("decimal(15,4)")
                        .HasColumnName("total_variance");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("SoId");

                    b.HasIndex("OutletId");

                    b.HasIndex("SoDate");

                    b.HasIndex("SoNumber")
                        .IsUnique();

                    b.ToTable("stock_opnames");
                });

            modelBuilder.Entity("WarehousePOS.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("supplier_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("SupplierCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("supplier_code");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("supplier_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("SupplierId");

                    b.HasIndex("SupplierCode")
                        .IsUnique();

                    b.ToTable("suppliers");
                });

            modelBuilder.Entity("WarehousePOS.Models.Customer", b =>
                {
                    b.HasOne("WarehousePOS.Models.CustomerTier", "Tier")
                        .WithMany("Customers")
                        .HasForeignKey("TierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Tier");
                });

            modelBuilder.Entity("WarehousePOS.Models.Order", b =>
                {
                    b.HasOne("WarehousePOS.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WarehousePOS.Models.CustomerTier", "CustomerTier")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerTierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WarehousePOS.Models.OrderType", "OrderType")
                        .WithMany("Orders")
                        .HasForeignKey("OrderTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarehousePOS.Models.Outlet", "Outlet")
                        .WithMany("Orders")
                        .HasForeignKey("OutletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("CustomerTier");

                    b.Navigation("OrderType");

                    b.Navigation("Outlet");
                });

            modelBuilder.Entity("WarehousePOS.Models.OrderDetail", b =>
                {
                    b.HasOne("WarehousePOS.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarehousePOS.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarehousePOS.Models.Product", null)
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId1");

                    b.HasOne("WarehousePOS.Models.ProductVariant", null)
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductVariantVariantId");

                    b.HasOne("WarehousePOS.Models.ProductVariant", "Variant")
                        .WithMany()
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("WarehousePOS.Models.OrderPayment", b =>
                {
                    b.HasOne("WarehousePOS.Models.Order", "Order")
                        .WithMany("OrderPayments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarehousePOS.Models.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarehousePOS.Models.PaymentMethod", null)
                        .WithMany("OrderPayments")
                        .HasForeignKey("PaymentMethodMethodId");

                    b.Navigation("Order");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("WarehousePOS.Models.OrderReturn", b =>
                {
                    b.HasOne("WarehousePOS.Models.Order", "Order")
                        .WithMany("OrderReturns")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("WarehousePOS.Models.Product", b =>
                {
                    b.HasOne("WarehousePOS.Models.ProductType", "Type")
                        .WithMany("Products")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("WarehousePOS.Models.ProductPrice", b =>
                {
                    b.HasOne("WarehousePOS.Models.Outlet", "Outlet")
                        .WithMany("ProductPrices")
                        .HasForeignKey("OutletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarehousePOS.Models.PriceTier", "PriceTier")
                        .WithMany("ProductPrices")
                        .HasForeignKey("PriceTierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarehousePOS.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarehousePOS.Models.Product", null)
                        .WithMany("Prices")
                        .HasForeignKey("ProductId1");

                    b.HasOne("WarehousePOS.Models.ProductVariant", null)
                        .WithMany("Prices")
                        .HasForeignKey("ProductVariantVariantId");

                    b.HasOne("WarehousePOS.Models.ProductVariant", "Variant")
                        .WithMany()
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Outlet");

                    b.Navigation("PriceTier");

                    b.Navigation("Product");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("WarehousePOS.Models.ProductStock", b =>
                {
                    b.HasOne("WarehousePOS.Models.StockLocation", "Location")
                        .WithMany("ProductStocks")
                        .HasForeignKey("LocationId");

                    b.HasOne("WarehousePOS.Models.Outlet", "Outlet")
                        .WithMany()
                        .HasForeignKey("OutletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarehousePOS.Models.Outlet", null)
                        .WithMany("ProductStocks")
                        .HasForeignKey("OutletId1");

                    b.HasOne("WarehousePOS.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarehousePOS.Models.Product", null)
                        .WithMany("Stocks")
                        .HasForeignKey("ProductId1");

                    b.HasOne("WarehousePOS.Models.ProductVariant", null)
                        .WithMany("Stocks")
                        .HasForeignKey("ProductVariantVariantId");

                    b.HasOne("WarehousePOS.Models.ProductVariant", "Variant")
                        .WithMany()
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Location");

                    b.Navigation("Outlet");

                    b.Navigation("Product");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("WarehousePOS.Models.ProductVariant", b =>
                {
                    b.HasOne("WarehousePOS.Models.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WarehousePOS.Models.Purchase", b =>
                {
                    b.HasOne("WarehousePOS.Models.Outlet", "Outlet")
                        .WithMany("Purchases")
                        .HasForeignKey("OutletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarehousePOS.Models.Supplier", "Supplier")
                        .WithMany("Purchases")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Outlet");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("WarehousePOS.Models.PurchaseDetail", b =>
                {
                    b.HasOne("WarehousePOS.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarehousePOS.Models.Product", null)
                        .WithMany("PurchaseDetails")
                        .HasForeignKey("ProductId1");

                    b.HasOne("WarehousePOS.Models.ProductVariant", null)
                        .WithMany("PurchaseDetails")
                        .HasForeignKey("ProductVariantVariantId");

                    b.HasOne("WarehousePOS.Models.Purchase", "Purchase")
                        .WithMany("PurchaseDetails")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarehousePOS.Models.ProductVariant", "Variant")
                        .WithMany()
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Product");

                    b.Navigation("Purchase");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("WarehousePOS.Models.ReturnDetail", b =>
                {
                    b.HasOne("WarehousePOS.Models.OrderDetail", "OrderDetail")
                        .WithMany()
                        .HasForeignKey("OrderDetailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarehousePOS.Models.OrderDetail", null)
                        .WithMany("ReturnDetails")
                        .HasForeignKey("OrderDetailId1");

                    b.HasOne("WarehousePOS.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarehousePOS.Models.OrderReturn", "OrderReturn")
                        .WithMany("ReturnDetails")
                        .HasForeignKey("ReturnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarehousePOS.Models.ProductVariant", "Variant")
                        .WithMany()
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("OrderDetail");

                    b.Navigation("OrderReturn");

                    b.Navigation("Product");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("WarehousePOS.Models.SoDetail", b =>
                {
                    b.HasOne("WarehousePOS.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarehousePOS.Models.Product", null)
                        .WithMany("SoDetails")
                        .HasForeignKey("ProductId1");

                    b.HasOne("WarehousePOS.Models.ProductVariant", null)
                        .WithMany("SoDetails")
                        .HasForeignKey("ProductVariantVariantId");

                    b.HasOne("WarehousePOS.Models.StockOpname", "StockOpname")
                        .WithMany("SoDetails")
                        .HasForeignKey("SoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarehousePOS.Models.ProductVariant", "Variant")
                        .WithMany()
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Product");

                    b.Navigation("StockOpname");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("WarehousePOS.Models.StockLocation", b =>
                {
                    b.HasOne("WarehousePOS.Models.Outlet", "Outlet")
                        .WithMany("StockLocations")
                        .HasForeignKey("OutletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Outlet");
                });

            modelBuilder.Entity("WarehousePOS.Models.StockLog", b =>
                {
                    b.HasOne("WarehousePOS.Models.StockLocation", "Location")
                        .WithMany("StockLogs")
                        .HasForeignKey("LocationId");

                    b.HasOne("WarehousePOS.Models.Outlet", "Outlet")
                        .WithMany()
                        .HasForeignKey("OutletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarehousePOS.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarehousePOS.Models.Product", null)
                        .WithMany("StockLogs")
                        .HasForeignKey("ProductId1");

                    b.HasOne("WarehousePOS.Models.ProductVariant", "Variant")
                        .WithMany("StockLogs")
                        .HasForeignKey("VariantId");

                    b.Navigation("Location");

                    b.Navigation("Outlet");

                    b.Navigation("Product");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("WarehousePOS.Models.StockOpname", b =>
                {
                    b.HasOne("WarehousePOS.Models.Outlet", "Outlet")
                        .WithMany("StockOpnames")
                        .HasForeignKey("OutletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Outlet");
                });

            modelBuilder.Entity("WarehousePOS.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("WarehousePOS.Models.CustomerTier", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("WarehousePOS.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("OrderPayments");

                    b.Navigation("OrderReturns");
                });

            modelBuilder.Entity("WarehousePOS.Models.OrderDetail", b =>
                {
                    b.Navigation("ReturnDetails");
                });

            modelBuilder.Entity("WarehousePOS.Models.OrderReturn", b =>
                {
                    b.Navigation("ReturnDetails");
                });

            modelBuilder.Entity("WarehousePOS.Models.OrderType", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("WarehousePOS.Models.Outlet", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("ProductPrices");

                    b.Navigation("ProductStocks");

                    b.Navigation("Purchases");

                    b.Navigation("StockLocations");

                    b.Navigation("StockOpnames");
                });

            modelBuilder.Entity("WarehousePOS.Models.PaymentMethod", b =>
                {
                    b.Navigation("OrderPayments");
                });

            modelBuilder.Entity("WarehousePOS.Models.PriceTier", b =>
                {
                    b.Navigation("ProductPrices");
                });

            modelBuilder.Entity("WarehousePOS.Models.Product", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("Prices");

                    b.Navigation("PurchaseDetails");

                    b.Navigation("SoDetails");

                    b.Navigation("StockLogs");

                    b.Navigation("Stocks");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("WarehousePOS.Models.ProductType", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WarehousePOS.Models.ProductVariant", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("Prices");

                    b.Navigation("PurchaseDetails");

                    b.Navigation("SoDetails");

                    b.Navigation("StockLogs");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("WarehousePOS.Models.Purchase", b =>
                {
                    b.Navigation("PurchaseDetails");
                });

            modelBuilder.Entity("WarehousePOS.Models.StockLocation", b =>
                {
                    b.Navigation("ProductStocks");

                    b.Navigation("StockLogs");
                });

            modelBuilder.Entity("WarehousePOS.Models.StockOpname", b =>
                {
                    b.Navigation("SoDetails");
                });

            modelBuilder.Entity("WarehousePOS.Models.Supplier", b =>
                {
                    b.Navigation("Purchases");
                });
#pragma warning restore 612, 618
        }
    }
}
